INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('a001', '자동차내부', '실내관리');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('a002', '자동차내부', '가죽');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('a003', '자동차내부', '틴팅필름');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('a004', '자동차내부', '매트클리닝');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('a005', '자동차내부', '탈취제');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('a006', '자동차내부', '찌든때');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('a007', '자동차내부', '필터');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b001', '자동차외부', '외부관리');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b002', '자동차외부', '워시 / 드라잉');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b003', '자동차외부', '광택코팅');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b004', '자동차외부', '휠 / 타이어 / 트림');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b005', '자동차외부', '외부유리');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b006', '자동차외부', '무광');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b007', '자동차외부', '새똥');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b008', '자동차외부', '벌레');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b009', '자동차외부', '유막제거');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b010', '자동차외부', '캠핑');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b011', '자동차외부', '컨버터블');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('b012', '자동차외부', '크롬 / 금속');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('c001', '세차도구', '버킷 / 워시');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('c002', '세차도구', '브러쉬');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('c003', '세차도구', '타월');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('c004', '세차도구', '어플패드');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('c005', '세차도구', '스프레이어 / 소분용기');
INSERT INTO `chemicalguys`.`category` (`categoryid`, `categroup`, `catename`) VALUES ('c006', '세차도구', '트렁크정리');

commit;